name: Release

on:
  release:
    types: [ published ]
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Determine Version
        id: release-version
        run: |
          echo "::set-output name=full::${{ github.ref_name }}"
          SIMPLE=$(echo ${{ github.ref_name }} | sed -e s/^v//)
          echo "::set-output name=simple::$SIMPLE"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: |
            3.7
            3.8
            3.9
            3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8
          if [ -f dev-requirements.txt ]; then pip install -r dev-requirements.txt; fi
          python3 -m pip install --upgrade build

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Build package
        run: python3 -m build

      - name: Upload Release Asset (source distribution)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/dbt-upsolver-${{ steps.release-version.outputs.simple }}.tar.gz
          asset_name: dbt_upsolver.tar.gz
          asset_content_type: application/tar+gz

      - name: Upload Release Asset (built distribution)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/dbt_upsolver-${{ steps.release-version.outputs.simple }}-py3-none-any.whl
          asset_name: dbt_upsolver-${{ steps.release-version.outputs.simple }}-py3-none-any.whl
          asset_content_type: application/whl
